version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: darkom_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: darkom_app
    ports:
      - "5439:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    ports:
      - "5050:80"
    depends_on:
      - postgres

  pipeline:
    build:
      context: .
      dockerfile: Dockerfile.pipeline
    container_name: darkom_pipeline_app
    depends_on:
      - postgres
    environment:
      DB_USER: postgres
      DB_PASSWORD: admin
      DB_HOST: postgres
      DB_PORT: 5439
      DB_NAME: darkom_app
    volumes:
      - .:/app
    restart: on-failure
    command: python script/staging.py
volumes:
  postgres_data: